app = 'alby-lite'
primary_region = 'lax'

[build]
  strategy = "rolling"
  max_unavailable = 1

[env]
  PORT = '8080'
  BASE_URL = "https://albylite.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "45s"
  interval = "60s"
  method = "GET"
  timeout = "5s"
  path = "/ping"
[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
